Dz1
Trifonix/2024-2-VK-EDU-Frontend-D-Trifonov pull request #1
Opened 2024-09-25 11:16 UTC by Trifonix

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @ivan-bir проверить его.

Что было сделано:
* Написана функция "правильных предложений"
* Написана функцией "повторяющихся чисел"
* Написана функция "человекоподобного размера" и тесты к ней

2024-09-26 15:16 UTC, Ivan-Bir requested changes

2024-09-26 15:16 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Возвращает false для неправильного типа данных', () => {
Начинают обычно с позитивных кейсов. Так чуть проще воспринимать код теста сверху вниз

2024-09-26 15:16 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  if (bytes === 0) {
Посмотри что происходит при значениях от 0 до 1. Покрыть тестом

2024-09-26 15:16 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  if (bytes === 0) {
*Так же обращу внимание, что обычно все данные хранятся в целых байтах и у нас не может быть такого (по логике вещей), что convertBytesToHuman(1.01) -> 1.01 B
Будет плюсиком, если обеспечишь такое поведение

2024-09-26 15:16 UTC, Ivan-Bir commented on correctSentence.js
> +  const goodText = text.charAt(0).toUpperCase() + text.slice(1);
1) Лучше использовать шаблонные строки `${var1} ${var2}`, это безопаснее с точки зрения возможных неявных преобразований
2) Нет проверки входных данных. Не учтены граничные случаи. Написать на это тест

2024-09-26 15:16 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  const goodNumbers = data.filter(item => data.indexOf(item) !== data.lastIndexOf(item));
1) В худшем случае, сложность этого алгоритма n^2, потому что метод поиска индекса всё также перебирает массив. То есть в худшем случае (все элементы уникальны), на каждую итерацию цикла будет происходить весь обход массива
2) Даже если у стрелочной функции один аргумент, то его принято оборачивать в скобки

2024-09-26 15:16 UTC, Ivan-Bir commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([10, 9, 10, 10, 9, 8])).toEqual([10, 9, 10, 10, 9]);
Тесты не покрывают граничные случаи. Давай это исправим

2024-09-26 19:57 UTC, Ivan-Bir submitted a review, later dismissed

2024-09-26 19:57 UTC, Ivan-Bir commented on correctSentence.js
> +  if (typeof text !== 'string' || text.trim() === '') return '';
Если тело условия или цикла в одну строку, то их всё равно принято оборачивать в {}. Это снижает когнитивную нагрузку читающему

2024-09-26 19:57 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  const goodNumbers = data.filter((item) => counts[item] > 1);
лишняя переменная

2024-09-26 19:57 UTC, Ivan-Bir commented on correctSentence.js
> +  const goodText = `${text.charAt(0).toUpperCase()}${text.slice(1)}`;
Не самое хорошее название для переменной)
Как и goodNumbers ниже

2024-09-26 19:57 UTC, Ivan-Bir commented on correctSentence.js
> +  else return goodText;
Избыточное else. Если выполнится условие, то функция вернет значение

2024-09-26 19:57 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  if (bytes < 1) {
Избыточное условие. Обработка значений меньше 1 есть выше

2024-09-26 19:57 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  bytes = (bytes < 1 && bytes !== 0) ? 1 : Math.floor(bytes);
0.1 байт, как и 0.999 это не 1, а 0

2024-09-26 19:57 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Обрабатывает значения меньше 1', () => {
Не только меньше 1, но и просто числа с плавающей запятой

2024-10-07 19:55 UTC, martinkomitsky commented
@Trifonix привет! будут ли исправления?

2024-11-10 11:08 UTC, martinkomitsky approved these changes
7

2024-11-10 11:08 UTC, merged